### ISSUE TITLE
`MergeRequestEvent` is missing `object_attributes.blocking_discussions_resolved`

### ISSUE THREAD

**Issue by hasit** [lawvs/gitlab-event-types#3]
In `MergeRequestEvent`, `MergeRequestAttributes` can contain `blocking_discussions_resolved`.

The key is documented here - https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events

**Comment by lawvs** [comment]
Thank you for your feedback! I have added the missing attribute in version 2.1.0.

Fixed in https://github.com/lawvs/gitlab-event-types/commit/720ccc408392b597f8f85217e425985bd85d279e
